GIS_P/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),

    path('admin/', admin.site.urls),  # 관리자 권한
    path('accounts/', include('accountapp.urls')),
    path('profileapp/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribe/', include('subscribeapp.urls')),
    path('likes/', include('likeapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = 'accountapp'

urlpatterns = [

    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),  # loginview는 장고에서 제공해주는 클래스

    path('logout/', LogoutView.as_view(), name='logout'),

    path('create/', AccountCreateView.as_view(), name='create'), # as_view를 선언하여 클래스를 사용할 수있게 한다.

    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),  # pk라는 이름에 숫자를 받는다. primary key

    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),

    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),

]

profileapp/urls.py
from django.urls import path

from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = 'profileapp'


urlpatterns = [
    path('create/', ProfileCreateView.as_view(), name='create'),
    path('update/<int:pk>', ProfileUpdateView.as_view(), name='update'),
]

accountapp/models.py
from django.db import models

# Create your models here.
# 엑셀 시트가 될꺼임

class newModel(models.Model):  # 장고에서 제공해주는 기본 모델 ( models.Model)
    text = models.CharField(max_length=255, null=False)  # 문자열을 입력받는 것을 만든다. max_length는 최대 문자열 길이를 설정

articleapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from projectapp.models import Project


class Article(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL,
                               related_name='article', null =True)
    # 유저를 가져오고 삭제시 유저의 게시글이 삭제되지 않고 null유저의 게시글로남고 target_user.article로 접근하게 해준다.

    project = models.ForeignKey(Project, on_delete=models.SET_NULL,
                                related_name='article', null=True , blank=True)
    #blank=True 는 굳이 설정해도 안해도 되게끔해줌
    title = models.CharField(max_length=200, null=True)
    image = models.ImageField(upload_to='article/')
    # 별도의 article폴더가 생성되면서 이미지가 그 폴더에 저장된다.
    content = models.TextField(null=True) #장문은 textfield를 쓴다.

    created_at = models.DateField(auto_now_add=True, null=True)
    # 언제 작성을 했는지, db가 찍히는 순간? 시간을 찍어준다.

    #게시물 생성시 최초 좋아요 갯수
    like = models.IntegerField(default=0)

accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm


class AccountCreationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)  # 부모 클래스의 변수를 다 받아오는 것

        self.fields['username'].disabled = True

accountapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from django.views.generic.list import MultipleObjectMixin

from accountapp.decorators import account_ownership_required
from accountapp.forms import AccountCreationForm
from accountapp.models import newModel
from articleapp.models import Article



class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('articleapp:list')
    template_name = 'accountapp/create.html' #어떤 html페이지를 쓸지

class AccountDetailView(DetailView, MultipleObjectMixin):
    model = User
    context_object_name = 'target_user'
    template_name = 'accountapp/detail.html'

    paginate_by = 20

    def get_context_data(self, **kwargs):
        article_list = Article.objects.filter(writer=self.object)
        return super().get_context_data(object_list=article_list, **kwargs)

has_ownership = [login_required, account_ownership_required] # 두가지 decorate를 적용시켜준다.

@method_decorator(has_ownership, 'get')  #함수에 쓰일 데코레이터를 메서드에도 적용시킨다. login을 어디에 적용시킬지도 작성해야한다.
@method_decorator(has_ownership, 'post')
class AccountUpdateView(UpdateView):
    model = User
    form_class = AccountCreationForm                            # 아이디도 바꿀수 있게 설정되어있어서 forms를 직접만들어 대신 넣어줌
    context_object_name = 'target_user'
    template_name = 'accountapp/update.html'

    def get_success_url(self):
        return reverse('accountapp:detail', kwargs={'pk': self.object.pk})

@method_decorator(has_ownership, 'get')  #함수에 쓰일 데코레이터를 메서드에도 적용시킨다. login을 어디에 적용시킬지도 작성해야한다.
@method_decorator(has_ownership, 'post')
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('articleapp:list')
    template_name = 'accountapp/delete.html'

accountapp/templates/accountapp/create.html
{%  extends 'base.html' %}
{% load bootstrap4 %} {# bootstrap4를 가져오겠다 #}

{% block content %}

    <div class="text-center mw-500 m-auto">
        <div class="m-5">  {# 기본적으로 제공해주는 클래스 #}
            <h4>Sign Up</h4>
        </div>
        <div>
            <form action="{% url 'accountapp:create' %}" method="post"> {# post형을 만들떄는 항상 토큰 넣기  / action은 요청을 보낼 경로             #}
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class="m-5">

                    <input type="submit" class = 'btn btn-outline-dark rounded-pill px-5'>
                </div>


            </form>
        </div>
    </div>

{%  endblock %}

accountapp/templates/accountapp/delete.html
{%  extends 'base.html' %}


{% block content %}

    <div class="text-center mw-500 m-auto">
        <div class="m-5">  {# 기본적으로 제공해주는 클래스 #}
            <h4>Quit</h4>
        </div>
        <div>
            <form action="{% url 'accountapp:delete' pk=target_user.pk %}" method="post"> {# post형을 만들떄는 항상 토큰 넣기  / action은 요청을 보낼 경로             #}
                {% csrf_token %}

                <div class="m-5">

                    <input type="submit" class = 'btn btn-danger rounded-pill px-5'>
                </div>


            </form>
        </div>
    </div>

{%  endblock %}

accountapp/templates/accountapp/detail.html
{%  extends 'base.html' %}

{% block content %}

    <div class="text-center mw-500 m-auto">
        <div class="m-5">  {# 기본적으로 제공해주는 클래스 #}
            {% if target_user.profile %}
                <img src="{{ target_user.profile.image.url }}"
                     class="profile_image m-4"
                     alt="profile image"> {# alt는 이미지가 안나올 경우 대신 나오는 문구 #}
                <h2 class="NNS_B">
                    {{ target_user.profile.nickname }}
                        {% if target_user == user %}
                            <a href="{% url 'profileapp:update' pk=target_user.profile.pk %}"
                            class="material-icons round_button">
                                edit
                            </a>
                        {% endif %}
                </h2>
                <h5>{{ target_user.profile.message }}</h5>
            {% else %}
            <h2>
                <a href="{% url 'profileapp:create' %} ">
                    Create Profile
                </a>
            </h2>
            {% endif %}
        </div>


        {% if user == target_user %}
{#            # 타겟 유저와 유저가 동일해야 작동됨#}

        <div>
            <a href="{% url 'accountapp:update' pk=target_user.pk %}"
            class="material-icons round_button mx-1">
                settings
            </a>

            <a href="{% url 'accountapp:delete' pk=target_user.pk %}"
            class="material-icons round_button mx-1">
                close
            </a>
        </div>

        {% endif %}
    </div>

    <div>
        {% include 'snippets/list_fragment.html' with article_list=object_list %}
    </div>

{%  endblock %}

accountapp/templates/accountapp/login.html
{%  extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div class="text-center mw-500 m-auto">
        <div class="m-5">  {# 기본적으로 제공해주는 클래스 #}
            <h4>login</h4>
        </div>
        <div>
            <form action="{% url 'accountapp:login' %}" method="post"> {# post형을 만들떄는 항상 토큰 넣기  / action은 요청을 보낼 경로             #}
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class="m-5">

                    <input type="submit" class = 'btn btn-outline-dark rounded-pill px-5'>
                </div>


            </form>
        </div>
    </div>

{%  endblock %}

accountapp/templates/accountapp/update.html
{%  extends 'base.html' %}
{% load bootstrap4 %} {# bootstrap4를 가져오겠다 #}

{% block content %}

    <div class="text-center mw-500 m-auto">
        <div class="m-5">  {# 기본적으로 제공해주는 클래스 #}
            <h4>Update info</h4>
        </div>
        <div>
            <form action="{% url 'accountapp:update' pk=target_user.pk %}" method="post"> {# post형을 만들떄는 항상 토큰 넣기  / action은 요청을 보낼 경로             #}
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class="m-5">

                    <input type="submit" class = 'btn btn-outline-dark rounded-pill px-5'>
                </div>


            </form>
        </div>
    </div>

{%  endblock %}