GIS_P/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),

    path('admin/', admin.site.urls),  # 관리자 권한
    path('accounts/', include('accountapp.urls')),
    path('profileapp/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribe/', include('subscribeapp.urls')),
    path('likes/', include('likeapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = 'accountapp'

urlpatterns = [

    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),  # loginview는 장고에서 제공해주는 클래스

    path('logout/', LogoutView.as_view(), name='logout'),

    path('create/', AccountCreateView.as_view(), name='create'), # as_view를 선언하여 클래스를 사용할 수있게 한다.

    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),  # pk라는 이름에 숫자를 받는다. primary key

    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),

    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),

]

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleapp'

#  accountapp:0000 에서 앞에accountapp같이 호출할때 app_name이 필요하다.

urlpatterns = [
    path('list/', ArticleListView.as_view(), name='list'),

    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),


]

projectapp/urls.py
from django.urls import path

from projectapp.views import ProjectCreateView, ProjectDetailView, ProjectListView

app_name = 'projectapp'
# 이걸해야 projectapp:xxxxx 이 가능하다.


urlpatterns = [
    path('create/', ProjectCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ProjectDetailView.as_view(), name='detail'),

    path('list/', ProjectListView.as_view(), name='list'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">

{% include 'head.html' %}

<body style="font-family: 'NanumSquareR'">



{% include 'header.html' %}

<hr>

{% for message in messages %}

    <div class="text-center">
        <div class="btn btn-{{ message.tags }} rounded-pill px-5">
            {{ message }}
        </div>

    </div>

{% endfor %}

{% block content %}
{% endblock %}

<hr>
{# 가로선 #}

{% include 'footer.html' %}

</body>
</html>

templates/footer.html
<div style="text-align:center">

    <div class="pragmatic_footer_botton">
        <span>공지사항</span>
        <span>제휴문의</span>
        <span>서비스 소개</span>
    </div>
    <div class="pragmatic_footer_logo">
        <h5>Pragmtic</h5>

    </div>

</div>

templates/head.html
{% load static %}
{#스태틱을 가져오겠다는 선언#}

<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width-device-width, initial-scale=1, shrink-to-fit=no">
    <title>Title</title>

    {#  bootstrap link  #}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    {#  GOOGLE FONTS LINK  #}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Zen+Tokyo+Zoo&display=swap" rel="stylesheet">

    {#  DEFAULT CSS LINK  #}
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

    {#  MATERIAL ICONS LINK  #}
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons"
      rel="stylesheet">


    <style>
        @font-face {
            font-family: 'NanumSquareR';
            src: local('NanumSquareR'),
            url("{% static 'fonts/NanumSquareR.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareEB';
            src: local('NanumSquareEB'),
            url("{% static 'fonts/NanumSquareEB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareB';
            src: local('NanumSquareB'),
            url("{% static 'fonts/NanumSquareB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareL';
            src: local('NanumSquareL'),
            url("{% static 'fonts/NanumSquareL.otf' %}") format("opentype");
        }
    </style>

</head>

templates/header.html
<div style="text-align:center">
    <div class="pragmatic_header_logo">

    {#    첫번쨰 숫자는 상하  두먼째 숫자는 좌우   #}
    {#  폰트가 적용이 안되면 cursive라는 폰트가 적용된다.  #}
        <a href="{% url 'home' %}">
            <h1>Pragmatic</h1>
        </a>

    </div>

    <div class="pragmatic_header_botton">
        <span class="mx-2">
            <a href="{% url 'articleapp:list' %}">
                Articles
            </a>
        </span>
        <span class="mx-2">
            <a href="{% url 'projectapp:list' %}">
                Projects
            </a>
        </span>
        {% if user.is_authenticated %}
            <span class="mx-2">
                <a href="{% url 'projectapp:list' %}">
                    Subscription
                </a>
            </span>
        {% endif %}
        {% if not user.is_authenticated %}   {# 로그인 확인 여부를 알아주는 객체 #}
        <span class="mx-2">
            <a href="{% url 'accountapp:login' %}">
                log-in
            </a>  {# a테그는 html 링크?테그를 만드는 것 #}
        </span>
        <span class="mx-2">
            <a href="{% url 'accountapp:create' %}">
                sign-up
            </a>
        </span>
        {% else %}
        <span class="mx-2">
            <a href="{% url 'accountapp:detail' pk=user.pk %}" >
                MyPage
            </a>
        </span>

        <span class="mx-2">
            <a  href="{% url 'accountapp:logout' %}" >
                log-out
            </a>
        </span>
        {% endif %}
    </div>

</div>